server:
  port: 8086

spring:
  application:
    name: auth-service

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: auth-service-client
            client-secret: SECRET_KEY
            authorization-grant-type: password
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/gestion-etudiants
