server:
  port: 7076

spring:
  application:
    name: auth-service

keycloak:
  server-url: http://keycloak:8080
  realm: gestion-etudiants
  client-id: auth-service-client
  client-secret: m5sM1pRaOmbIDPvbJEaX3FPGyo77BgxU

management:
  endpoints:
    web:
      exposure:
        include: health,info
