server:
  port: 7076

spring:
  application:
    name: auth-service

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: auth-service-client
            client-secret: CLIENT_SECRET
            authorization-grant-type: password
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/gestion-etudiants

management:
  endpoints:
    web:
      exposure:
        include: health,info
