server:
  port: 7070

spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: etudiant-service
          uri: lb://ETUDIANT-SERVICE
          predicates:
            - Path=/api/students/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
