server:
  port: 7070

spring:
  application:
    name: gateway-server

  main:
    web-application-type: reactive  

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/gestion-etudiants

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          refresh-rate: 5000

      routes:
        - id: auth-service
          uri: lb://auth-servive
          predicates:
            - Path=/api/auth/**

            
        - id: etudiant-service
          uri: lb://etudiant-service
          predicates:
            - Path=/api/etudiants/**,/api/inscriptions/**


        - id: scolarite-service
          uri: lb://scolarite-service
          predicates:
            - Path=/api/matieres/**,/api/classes/**, /api/classe-matieres/**


        - id: enseignant-service
          uri: lb://enseignant-service
          predicates:
            - Path=/api/enseignants/**,/api/affectations/**


        - id: notes-service
          uri: lb://notes-service
          predicates:
            - Path=/api/notes/**,/api/evaluations/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"

      httpclient:
        connect-timeout: 5000
        response-timeout: 10s

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
